name: Read Secrets from Azure Key Vault

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  
jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install required Python libraries
      - name: Install dependencies
        run: |
          pip install azure-identity azure-keyvault-secrets lxml

      # Step 4: Authenticate and retrieve secrets
      - name: Retrieve Secrets from Azure Key Vault
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          python read_secrets.py
