name: Upload Secret to Azure Key Vault

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  upload-secret:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository (optional)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      # Step 3: Upload a secret to Azure Key Vault
      - name: Upload Secret to Azure Key Vault
        shell: pwsh
        run: |
          az keyvault secret set ' 
            --vault-name ${{ secrets.AZURE_KEY_VAULT }} '
            --name SECRET_TO_UPLOAD '
            --value "${{ secrets.SECRET_TO_UPLOAD }}"
            
     # Step 4: debug log for upload secret to Azure Key Vault
      - name: Debug Secret Upload
        shell: pwsh
        run: |
         Write-Host "Vault Name: ${{ secrets.AZURE_KEY_VAULT }}"
         Write-Host "Uploading secret MY_SECRET_NAME"
